/**
 * The Phase 4.1 mutations (the shadow order-book recorder and its report), checked by `npm run phase4:mutations` with the older ones. Every id starts with `s4`.
 * Each applies ONE deliberate defect and expects the named tests to fail. The two real-Postgres files only run when PG_TEST_URL is set, so run the check
 * with it set: `PG_TEST_URL=postgres://… npm run phase4:mutations -- s4M1 s4M2`.
 */
import type { Mutation } from "./mutations-4-0d";
const L = "src/lib/phase4/shadow/";
const T = { fill: "tests/phase4-shadow-fill.test.ts", sch: "tests/phase4-shadow-schedule.test.ts", job: "tests/phase4-shadow-job.test.ts", rep: "tests/phase4-shadow-report.test.ts", bd: "tests/phase4-shadow-boundaries.test.ts", sql: "tests/phase4-shadow-sql.test.ts", iso: "tests/phase4-isolation.test.ts", http: "tests/phase4-http.test.ts" };
const m = (id: string, what: string, file: string, find: string, replace: string, tests: string[]): Mutation => ({ id, what, edits: [{ file: file.includes("/") ? file : L + file, find, replace }], tests });

export const MUTATIONS_4_1: Mutation[] = [
  // ── fill walk
  m("s4F1", "the walk ignores the depth of a level (fabricates liquidity)", "fill.ts", "const take = Math.min(remaining / price, size);", "const take = remaining / price;", [T.fill]),
  m("s4F2", "the hypothetical buy walks the bid side", "fill.ts", "walkBuy(book.asks, s,", "walkBuy(book.bids, s,", [T.fill]),
  m("s4F3", "slippage versus the wallet has the wrong sign", "fill.ts", "r6(avg - ref.sourcePrice)", "r6(ref.sourcePrice - avg)", [T.fill]),
  m("s4F4", "filled_share says 1 for any fill, however partial", "fill.ts", "filled_share: r6(Math.min(1, spent / usd))", "filled_share: r6(shares > 0 ? 1 : 0)", [T.fill, T.rep]),
  m("s4F5", "the fee is charged at one fixed price instead of at each level taken", "fill.ts", "fee += takerFee(take, price, ref.feeRate);", "fee += takerFee(take, 0.5, ref.feeRate);", [T.fill]),
  m("s4F6", "a crossed book still gets hypothetical fills", "fill.ts", 'if (book.state === "CROSSED") return null;', "", [T.fill]),
  m("s4F7", "the limit price is the best ask touched, not the worst", "fill.ts", "spent += take * price; shares += take; fee += takerFee(take, price, ref.feeRate); remaining -= take * price; worst = price;", "spent += take * price; shares += take; fee += takerFee(take, price, ref.feeRate); remaining -= take * price; worst = worst ?? price;", [T.fill]),
  m("s4F8", "the minimum-order flag is inverted", "fill.ts", "shares < ref.minOrderSize - EPS", "shares > ref.minOrderSize - EPS", [T.fill]),
  m("s4F9", "a fill is not reported against the mid", "fill.ts", "slippage_vs_mid: avg !== null && ref.mid !== null ? r6(avg - ref.mid) : null,", "slippage_vs_mid: null,", [T.fill]),
  // ── book normalisation
  m("s4B1", "bids are not sorted best first", "book.ts", "const bids = b.levels.sort((x, y) => y[0] - x[0]);", "const bids = b.levels;", [T.fill]),
  m("s4B2", "asks are not sorted best first", "book.ts", "const asks = a.levels.sort((x, y) => x[0] - y[0]);", "const asks = a.levels;", [T.fill]),
  m("s4B3", "a locked book (bid = ask) is called crossed", "book.ts", "bestBid! > bestAsk!", "bestBid! >= bestAsk!", [T.fill]),
  m("s4B4", "levels with an impossible price or size are kept", "book.ts", "|| !(p > 0 && p < 1) || !(s > 0)) { dropped++; continue; }", ") { dropped++; continue; }", [T.fill]),
  m("s4B5", "a repeated price overwrites instead of adding up", "book.ts", "merged.set(k, (merged.get(k) ?? 0) + s);", "merged.set(k, s);", [T.fill]),
  m("s4B6", "an error body is read as an empty book", "book.ts", "if (o.bids === undefined && o.asks === undefined) return null;", "", [T.fill]),
  m("s4B7", "the mid is the ask", "book.ts", "r6((bestAsk! + bestBid!) / 2)", "r6(bestAsk!)", [T.fill]),
  m("s4B8", "the stored copy keeps one level too many", "book.ts", "ls.slice(0, n).map", "ls.slice(0, n + 1).map", [T.fill, T.job]),
  // ── fee
  m("s4E1", "basis points are converted with the wrong unit", "fee.ts", "export const BPS_PER_UNIT = 10_000;", "export const BPS_PER_UNIT = 100;", [T.fill]),
  m("s4E2", "a zero fee is reported as an observed rate, not fee-free", "fee.ts", "feesEnabled: bps > 0,", "feesEnabled: true,", [T.fill]),
  m("s4E3", "an unknown fee is assumed at the conservative paper rate, not the realistic one", "fee.ts", "export const PAPER_FEE_MODE = MODES.REALISTIC;", "export const PAPER_FEE_MODE = MODES.CONSERVATIVE;", [T.fill, T.job]),
  m("s4E4", "a negative fee rate is accepted", "fee.ts", "Number.isFinite(n) && n >= 0 ? n : null", "Number.isFinite(n) ? n : null", [T.fill]),
  // ── schedule
  m("s4S1", "a snapshot is not due exactly at its due time", "schedule.ts", "if (dueAtSec > nowSec || have.has(", "if (dueAtSec >= nowSec || have.has(", [T.sch]),
  m("s4S2", "exactly 120 s late becomes MISSED", "schedule.ts", "late: nowSec - dueAtSec > maxLate }", "late: nowSec - dueAtSec >= maxLate }", [T.sch]),
  m("s4S3", "rows that exist are planned again", "schedule.ts", "|| have.has(rowKey(s.id, off))) continue;", ") continue;", [T.sch, T.job]),
  m("s4S4", "EXIT signals are measured", "schedule.ts", 's.kind !== "EXIT" && (minScore', "(minScore", [T.sch]),
  m("s4S5", "the minimum score is exclusive", "schedule.ts", "s.copyScore >= minScore", "s.copyScore > minScore", [T.sch]),
  m("s4S6", "newest due first instead of oldest", "schedule.ts", "all.sort((a, b) => a.dueAtSec - b.dueAtSec ||", "all.sort((a, b) => b.dueAtSec - a.dueAtSec ||", [T.sch]),
  m("s4S7", "the snapshot cap is not applied", "schedule.ts", ".slice(0, o.maxSnapshots)", ".slice(0, o.maxSnapshots + 1000)", [T.sch, T.job]),
  m("s4S8", "isTooLate is inclusive", "schedule.ts", "nowSec - dueAtSec > maxLateS;", "nowSec - dueAtSec >= maxLateS;", [T.sch]),
  m("s4S9", "the missed cap is not applied", "schedule.ts", ".slice(0, o.maxMissed)", ".slice(0, o.maxMissed + 1000)", [T.sch]),
  // ── flags and constants
  m("s4C1", "the third offset is 600 s", "config.ts", "OFFSETS_S: readonly number[] = [0, 60, 300];", "OFFSETS_S: readonly number[] = [0, 60, 600];", [T.sch]),
  m("s4C2", "a snapshot may be 300 s late", "config.ts", "export const MAX_LATE_S = 120;", "export const MAX_LATE_S = 300;", [T.sch]),
  m("s4C3", "SHADOW_BOOKS=true switches the job on", "config.ts", 'if (raw !== "1") return off(', 'if (raw !== "1" && raw !== "true") return off(', [T.job]),
  m("s4C4", "any non-zero SHADOW_BOOKS switches the job on", "config.ts", 'if (raw !== "1") return off(', 'if (raw === "0") return off(', [T.job]),
  m("s4C5", "the minimum score defaults to 50", "config.ts", "env.SHADOW_BOOKS_MIN_SCORE, 0, (n) =>", "env.SHADOW_BOOKS_MIN_SCORE, 50, (n) =>", [T.job]),
  m("s4C6", "the daily budget defaults to 200", "config.ts", "export const DEFAULT_DAILY_REQUESTS = 20_000;", "export const DEFAULT_DAILY_REQUESTS = 200;", [T.job]),
  m("s4C7", "a minimum score above 100 is accepted", "config.ts", "(n) => n >= 0 && n <= 100)", "(n) => n >= 0)", [T.job]),
  m("s4C8", "a fractional daily budget is accepted", "config.ts", "Number.isInteger(n) && n >= 1", "n >= 1", [T.job]),
  m("s4C9", "the daily request budget has no ceiling", "config.ts", "n >= 1 && n <= 172_800)", "n >= 1)", [T.job]),
  m("s4C10", "the recorded depth is 5 levels", "config.ts", "export const DEPTH_LEVELS = 10;", "export const DEPTH_LEVELS = 5;", [T.job]),
  m("s4C11", "retention is 4,500 days", "config.ts", "export const RETENTION_DAYS = 45;", "export const RETENTION_DAYS = 4500;", [T.job]),
  m("s4C12", "the per-cycle snapshot cap is 2,000", "config.ts", "export const MAX_SNAPSHOTS_PER_CYCLE = 20;", "export const MAX_SNAPSHOTS_PER_CYCLE = 2000;", [T.job]),
  // ── store
  m("s4T1", "the look-back is ten years (a fresh enable back-fills history)", "store.ts", "lookbackS = LOOKBACK_S)", "lookbackS = 315_360_000)", [T.job]),
  m("s4T2", "an existing row is overwritten by a second write", "store.ts", "ignoreDuplicates: true", "ignoreDuplicates: false", [T.job]),
  m("s4T3", "the signal window is paged without a limit on the number of pages", "store.ts", "page < MAX_PAGES;", "page < 100_000;", [T.job]),
  m("s4T4", "the daily request count reads only the first page", "store.ts", "if (rows.length < 1000) return sum;", "return sum;", [T.job]),
  m("s4T5", "pruning deletes every row of a signal, not only the old ones", "store.ts", '.delete().in("signal_id", ids).lt("due_at", cutoffIso);', '.delete().in("signal_id", ids);', [T.job]),
  m("s4T6", "pruning selects without a batch limit", "store.ts", '.order("due_at", { ascending: true }).limit(batch);', '.order("due_at", { ascending: true });', [T.job]),
  m("s4T7", "pruning removes rows younger than the cutoff", "store.ts", '.lt("due_at", cutoffIso).order("due_at"', '.lt("due_at", "9999-01-01T00:00:00Z").order("due_at"', [T.job, T.sql]),
  m("s4T8", "the window includes EXIT signals at the query (and the planner is the only guard)", "store.ts", '.neq("kind", "EXIT")', "", [T.job]),
  // ── snapshot
  m("s4N1", "a 404 is recorded as an error, not as NOT_FOUND", "snapshot.ts", 'row.status = b.kind === "NOT_FOUND" ? "NOT_FOUND" : "ERROR"; return finish();', 'row.status = "ERROR"; return finish();', [T.job]),
  m("s4N2", "a 429 is not a refusal", "snapshot.ts", ' || r.kind === "RATE_LIMITED";', ";", [T.job]),
  m("s4N3", "the fee rate is asked even for a crossed book", "snapshot.ts", 'if (book.state !== "CROSSED" && book.asks.length) {', "if (book.asks.length) {", [T.job]),
  m("s4N4", "the fee cache is not used", "snapshot.ts", "let bps = o.fees.get(d.tokenId, takenAt);", "let bps: number | null = null;", [T.job]),
  m("s4N5", "request_count is always 1", "snapshot.ts", "row.request_count = o.http.requests - req0;", "row.request_count = 1;", [T.job]),
  m("s4N6", "the whole book is stored, not the top levels", "snapshot.ts", "topLevels(book.bids, DEPTH_LEVELS)", "book.bids", [T.job]),
  m("s4N7", "the fill walk uses only the stored levels", "snapshot.ts", "row.fills = fillsFor(book, o.sizesUsd ?? SIZES_USD, { sourcePrice: d.sourcePrice, feeRate: rate });", "row.fills = fillsFor({ ...book, asks: book.asks.slice(0, DEPTH_LEVELS) }, o.sizesUsd ?? SIZES_USD, { sourcePrice: d.sourcePrice, feeRate: rate });", [T.job]),
  m("s4N8", "the fee cache never expires", "snapshot.ts", "nowSec - e.at < this.ttlS", "true", [T.job]),
  m("s4N9", "the fee cache is unbounded", "snapshot.ts", "this.m.size >= this.max", "false", [T.job]),
  m("s4N10", "the fee-rate refusal is ignored", "snapshot.ts", "else if (refusal(f)) refused = {", "else if (false) refused = {", [T.job]),
  // ── job
  m("s4J1", "the off job runs anyway", "job.ts", "if (!this.d.config) return { ...stats, off: true };", "", [T.job]),
  m("s4J2", "no busy guard", "job.ts", 'if (this.busy) return { ...stats, skipped: "BUSY" };', "", [T.job]),
  m("s4J3", "a refusal does not end the cycle", "job.ts", "stats.refused = true; this.consecutiveRefusals++;", "stats.refused = true; this.consecutiveRefusals++; continue;", [T.job]),
  m("s4J4", "a refusal does not pause the job", "job.ts", "this.pausedUntil = this.nowSec() + pause;", "this.pausedUntil = 0;", [T.job]),
  m("s4J5", "Retry-After is ignored", "job.ts", "Math.ceil((r.refused.retryAfterMs ?? 0) / 1000)", "0", [T.job]),
  m("s4J6", "the pause does not double", "job.ts", "REFUSAL_PAUSE_S * 2 ** (this.consecutiveRefusals - 1)", "REFUSAL_PAUSE_S", [T.job]),
  m("s4J7", "the daily request budget is ignored", "job.ts", "if (spent() + 2 > cfg.dailyRequests) {", "if (false) {", [T.job]),
  m("s4J8", "the daily count is not read back after a restart", "job.ts", "this.used = await requestsSince(this.d.db, `${day}T00:00:00.000Z`);", "this.used = 0;", [T.job]),
  m("s4J9", "no time budget per cycle", "job.ts", "if (this.clockMs() - t0 >= CYCLE_BUDGET_MS) break;", "", [T.job]),
  m("s4J10", "a snapshot made late by the cycle itself is still taken", "job.ts", "if (isTooLate(due.dueAtSec, at)) {", "if (false) {", [T.job]),
  m("s4J11", "pruning runs every cycle", "job.ts", "if (now - this.lastPrune >= PRUNE_EVERY_S) {", "if (true) {", [T.job]),
  m("s4J12", "the polite client retries a 429", "job.ts", "retryRateLimited: false,", "retryRateLimited: true,", [T.job]),
  m("s4J13", "the polite client keeps every request event (an unbounded list in a long-lived worker)", "job.ts", "recordEvents: false,", "recordEvents: true,", [T.job]),
  m("s4J15", "the safe wrapper rethrows", "job.ts", "return { failed: msg };", "throw e;", [T.job]),
  m("s4J16", "the job does not identify itself", "job.ts", "userAgent: USER_AGENT,", "", [T.job]),
  m("s4J17", "a paused job still asks", "job.ts", "if (now < this.pausedUntil) {", "if (false) {", [T.job]),
  m("s4J18", "a success does not reset the refusal count", "job.ts", "this.consecutiveRefusals = 0;\n    }", "}", [T.job]),
  m("s4J19", "the status heartbeat of a failed cycle is not recorded", "job.ts", 'try { await beat(o.db, JSON.stringify({ at: new Date(now() * 1000).toISOString(), ok: false,', 'try { if (false) await beat(o.db, JSON.stringify({ at: new Date(now() * 1000).toISOString(), ok: false,', [T.job]),
  m("s4J20", "a pruning failure fails the whole cycle", "job.ts", "catch (e) { this.log(`shadow books: pruning failed (${(e as Error).message})`); }", "catch (e) { throw e; }", [T.job]),
  // ── http client additions
  m("s4H1", "retryRateLimited is ignored", "src/lib/phase4/http.ts", "if (res.status === 429 && !this.retryRateLimited) return done(last, attempt);", "", [T.bd, T.job]),
  m("s4H2", "recordEvents is ignored", "src/lib/phase4/http.ts", "if (this.recordEvents) this.events.push(", "this.events.push(", [T.bd, T.job]),
  m("s4H3", "the reported Retry-After is the capped value", "src/lib/phase4/http.ts", "...(serverRetryAfterMs ? { retryAfterMs: serverRetryAfterMs } : {}) };", "...(serverRetryAfterMs ? { retryAfterMs } : {}) };", [T.bd, T.job]),
  { id: "s4H4", what: "the 500 ms floor on the global gap is removed and the job asks every 100 ms", edits: [{ file: "src/lib/phase4/http.ts", find: "this.gap = Math.max(500, o.minIntervalMs ?? 500);", replace: "this.gap = Math.max(50, o.minIntervalMs ?? 50);" }, { file: L + "job.ts", find: "minIntervalMs: 500,", replace: "minIntervalMs: 100," }], tests: [T.job, T.bd] },
  // ── report arithmetic
  m("s4R1", "depth within 1 point excludes a level exactly 1 point away", "report.ts", "points / PTS + 1e-9", "points / PTS - 1e-9", [T.rep]),
  m("s4R2", "the interval ignores clustering", "report.ts", "Math.sqrt((g / (g - 1)) * ss) / n", "Math.sqrt(ss * 0.5) / n", [T.rep]),
  m("s4R3", "a lower bound of exactly 0 is called UNDERSTATED", "report.ts", 'd.lo > 0 ? "UNDERSTATED"', 'd.lo >= 0 ? "UNDERSTATED"', [T.rep]),
  m("s4R4", "3 pairs are enough for a verdict", "report.ts", "export const MIN_PAIRS = 30;", "export const MIN_PAIRS = 3;", [T.rep]),
  m("s4R5", "2 markets are enough for a verdict", "report.ts", "MIN_CLUSTERS = 10;", "MIN_CLUSTERS = 2;", [T.rep]),
  m("s4R6", "a tie between offsets goes to the later one", "report.ts", "|| a - b)[0];", "|| b - a)[0];", [T.rep]),
  m("s4R7", "costs are not normalised by the fill price", "report.ts", "(x / fill) * 100;", "(x / 1) * 100;", [T.rep]),
  m("s4R8", "a fee is compared when only one side observed it", "report.ts", "p.obsFeeObserved && p.paperFeeObserved", "true", [T.rep]),
  m("s4R9", "every offset is paired, not only the one nearest the paper latency", "report.ts", "if (row.offset_s === this.pairOffset && paper) this.pair(", "if (paper) this.pair(", [T.rep]),
  m("s4R10", "a paper UNFILLED row is paired", "report.ts", '(p.status !== "FILLED" && p.status !== "PARTIALLY_FILLED") ||', "", [T.rep]),
  m("s4R11", "unfillable counts only the nothing-filled cases", "report.ts", "if (f.filled_share < 1 - 1e-9) a.notFull++;", "if (f.filled_share <= 0) a.notFull++;", [T.rep]),
  m("s4R12", "spread is reported in price units, not points", "report.ts", "r.spread * PTS", "r.spread", [T.rep]),
  m("s4R13", "MISSED rows are not counted in the MISSED share", "report.ts", 'if (s === "MISSED") missed += n;', "", [T.rep]),
  m("s4R14", "the paper latency is 110 s", "report.ts", "MODES.REALISTIC.decisionLatencySec + MODES.REALISTIC.executionLatencySec", "MODES.REALISTIC.decisionLatencySec + 100", [T.rep]),
  m("s4R15", "the report mixes paper and observed in the wrong direction (observed minus paper reversed)", "report.ts", "const diffs = ps.map((p) => obsOf(p) - paperOf(p));", "const diffs = ps.map((p) => paperOf(p) - obsOf(p));", [T.rep]),
  m("s4R16", "the paired comparison uses the $10 fill instead of $100", "report.ts", 'const size = this.sizes.includes(100) ? 100 : this.sizes[this.sizes.length - 1];', "const size = this.sizes[0];", [T.rep]),
  m("s4R17", "the ALL group is missing", "report.ts", 'return ["ALL", `cat:${m.category}`', 'return [`cat:${m.category}`', [T.rep]),
  m("s4R18", "the console is allowed more than 60 lines (the 'what this is not' block is dropped)", "report.ts", "L.push(...WHAT_THIS_IS_NOT); return L;\n}", "return L;\n}", [T.rep]),
  // ── report CLI
  m("s4L1", "the report reads only the first page", "report-cli.ts", "if (rows.length < REPORT_PAGE) break;", "break;", [T.rep]),
  m("s4L2", "the paper join uses the wrong mode", "report-cli.ts", '.eq("mode", "REALISTIC")', '.eq("mode", "IDEAL")', [T.rep]),
  m("s4L3", "numeric strings from Postgres are not coerced", "report-cli.ts", "const N = (v: unknown): number | null => (v === null || v === undefined ? null : Number.isFinite(Number(v)) ? Number(v) : null);", "const N = (v: unknown): number | null => v as number | null;", [T.rep, T.sql]),
  m("s4L4", "the row cap is not enforced", "report-cli.ts", "if (seen >= o.maxRows) throw", "if (false) throw", [T.rep]),
  m("s4L5", "a missing database variable is not noticed", "report-cli.ts", "if (!d.db && !(env.NEXT_PUBLIC_SUPABASE_URL && env.SUPABASE_SERVICE_ROLE_KEY)) {", "if (false) {", [T.rep]),
  m("s4L6", "the report's category is the signal kind", "report-cli.ts", "category: categorize({ title: s.title, slug: s.slug }).category", "category: String(s.kind)", [T.rep]),
  // ── worker wiring and the migration
  m("s4W1", "the worker starts the shadow job whatever the flag says", "worker/ws-listener.ts", "if (shadow.on) {", "if (true) {", [T.job]),
  m("s4W2", "the migration lets the public read the table", "supabase/migrations/0012_shadow_books.sql", "alter table shadow_books enable row level security;", 'alter table shadow_books enable row level security;\ncreate policy "public read shadow_books" on shadow_books for select using (true);', [T.bd, T.sql]),
  m("s4W3", "the service role may update", "supabase/migrations/0012_shadow_books.sql", "grant select, insert, delete on table shadow_books", "grant select, insert, update, delete on table shadow_books", [T.bd, T.sql]),
  m("s4W4", "row-level security is not enabled", "supabase/migrations/0012_shadow_books.sql", "alter table shadow_books enable row level security;", "", [T.bd, T.sql]),
  m("s4W5", "anon keeps its default grants", "supabase/migrations/0012_shadow_books.sql", "revoke all on table shadow_books from public, anon, authenticated;", "", [T.bd, T.sql]),
  m("s4W6", "an OK row may be crossed", "supabase/migrations/0012_shadow_books.sql", "best_bid <= best_ask)),", "true)),", [T.sql]),
  m("s4W7", "a MISSED row may carry data", "supabase/migrations/0012_shadow_books.sql", "status <> 'MISSED' or (bids is null", "status <> 'MISSED' or (true or bids is null", [T.sql]),
  m("s4W8", "the status vocabulary admits anything", "supabase/migrations/0012_shadow_books.sql", "check (status in ('OK','EMPTY_BOOK','ONE_SIDED','CROSSED','NOT_FOUND','ERROR','REFUSED','MISSED'))", "check (true)", [T.sql]),
  m("s4W9", "the key is not unique per offset", "supabase/migrations/0012_shadow_books.sql", "primary key (signal_id, offset_s),", "primary key (signal_id, offset_s, due_at),", [T.sql]),
];
